apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-convert-app-deployment
  labels:
    app: temp-convert-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  temp-convert-app
  template:
    metadata:
      labels:
        app: temp-convert-app
    spec:
      containers:
        - name: temp-convert-app-ctr
          image: rootovertwo/temp-convert-app
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: temp-convert-app-service
spec:
  selector:
    app: temp-convert-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort

