apiVersion: v1
kind: Service
metadata:
  name: temp-convert-app-service
spec:
  selector:
    app: temp-convert-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort
